### ISSUE TITLE
Unable to parse data with xmltodict 0.14.1

### ISSUE THREAD

**Issue by fursov** [saaste/fmi-weather-client#58]
Home assistant has updated the packet version to 0.14.1 and this library has stopped to work (it is used by the [fmi](https://github.com/anand-p-r/fmi-hass-custom) custom component).
Would it be possible to update the dependency to 0.14.1?

**Comment by fursov** [comment]
I created PR #59 for the issue.

**Comment by saaste** [comment]
I have merged your changes and also added some of my own too. While I was at it, I also dropped Python 3.8 support, as it is already past its of end-of-life cycle. There is now a [0.4.0](https://pypi.org/project/fmi-weather-client/0.4.0/) version available in PyPi which includes these changes.

Thanks for the help! Hopefully this solves the problems. ☺️ 🙇‍♂️

**Comment by fursov** [comment]
> @fursov I have merged your changes and also added some of my own too. While I was at it, I also dropped Python 3.8 support, as it is already past its of end-of-life cycle. There is now a [0.4.0](https://pypi.org/project/fmi-weather-client/0.4.0/) version available in PyPi which includes these changes.
> 
> Thanks for the help! Hopefully this solves the problems. ☺️ 🙇‍♂️

Thanks for your library! Yes, now the HASS plugin works locally in my setup, we just need to wait when upstream repo updates the dependencies.
